// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKeyValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddKeyValue'](arg1, arg2, arg3);
}

export function CreateBucket(arg1) {
  return window['go']['main']['App']['CreateBucket'](arg1);
}

export function GetValue(arg1, arg2) {
  return window['go']['main']['App']['GetValue'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
